CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,username VARCHAR(50) UNIQUE NOT NULL,full_name VARCHAR(150) NOT NULL,role VARCHAR(40) NOT NULL CHECK(role IN ('Master Administrator','Maker','Approver','Viewer')),password_hash TEXT NOT NULL,is_active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS divisions(id BIGSERIAL PRIMARY KEY,name VARCHAR(150) UNIQUE NOT NULL,is_active BOOLEAN DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS vendors(id BIGSERIAL PRIMARY KEY,vendor_name VARCHAR(180) NOT NULL,job_name VARCHAR(250),contract_no VARCHAR(120),pic_name VARCHAR(150),pic_phone VARCHAR(60),is_active BOOLEAN DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS number_sequences(sequence_type VARCHAR(30) NOT NULL,year INT NOT NULL,last_number INT NOT NULL DEFAULT 0,PRIMARY KEY(sequence_type,year));
CREATE TABLE IF NOT EXISTS journal_registers(id BIGSERIAL PRIMARY KEY,journal_no VARCHAR(40) UNIQUE NOT NULL,journal_date DATE NOT NULL,cost_name VARCHAR(250) NOT NULL,amount NUMERIC(20,2) NOT NULL CHECK(amount>=0),payee VARCHAR(200) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'AKTIF' CHECK(status IN('AKTIF','BATAL')),created_by BIGINT REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),cancel_reason TEXT,cancelled_by BIGINT REFERENCES users(id),cancelled_at TIMESTAMPTZ);
-- Register Jurnal sengaja TIDAK memiliki foreign key ke Kartu Kontrol, OPE, atau Tagihan.
CREATE TABLE IF NOT EXISTS control_cards(id BIGSERIAL PRIMARY KEY,card_no VARCHAR(50) UNIQUE NOT NULL,job_name VARCHAR(250) NOT NULL,contract_no VARCHAR(120),vendor_name VARCHAR(180),vendor_pic_name VARCHAR(150),vendor_pic_phone VARCHAR(60),user_name VARCHAR(150) NOT NULL,division_name VARCHAR(150) NOT NULL,procurement_value NUMERIC(20,2) NOT NULL,tax_status VARCHAR(30),payment_method VARCHAR(30),duration_type VARCHAR(20),duration_months INT,status VARCHAR(40) NOT NULL DEFAULT 'DRAFT',created_by BIGINT REFERENCES users(id),created_at TIMESTAMPTZ DEFAULT NOW(),submitted_at TIMESTAMPTZ,approved_at TIMESTAMPTZ,approved_by BIGINT REFERENCES users(id),return_reason TEXT);
CREATE TABLE IF NOT EXISTS control_card_terms(id BIGSERIAL PRIMARY KEY,control_card_id BIGINT REFERENCES control_cards(id),term_no INT,progress_condition TEXT,payment_percentage NUMERIC(8,4),term_value NUMERIC(20,2),manual_override BOOLEAN DEFAULT FALSE,override_reason TEXT);
CREATE TABLE IF NOT EXISTS invoices(id BIGSERIAL PRIMARY KEY,control_card_id BIGINT REFERENCES control_cards(id),term_no INT,billing_period VARCHAR(20),progress_condition TEXT,payment_percentage NUMERIC(8,4),invoice_value NUMERIC(20,2) NOT NULL,pph2 NUMERIC(20,2),vendor_account VARCHAR(100),payment_date DATE,notes TEXT,approval_status VARCHAR(30) DEFAULT 'DRAFT',journal_status VARCHAR(30) DEFAULT 'BELUM DIBUAT JURNAL',created_by BIGINT REFERENCES users(id),created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS ope_cards(id BIGSERIAL PRIMARY KEY,ope_no VARCHAR(50) UNIQUE NOT NULL,job_name VARCHAR(250) NOT NULL,user_name VARCHAR(150) NOT NULL,division_name VARCHAR(150) NOT NULL,ope_value NUMERIC(20,2) NOT NULL,tax_status VARCHAR(30),stage_count INT,status VARCHAR(40) DEFAULT 'DRAFT',created_by BIGINT REFERENCES users(id),created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS ope_invoices(id BIGSERIAL PRIMARY KEY,ope_card_id BIGINT REFERENCES ope_cards(id),stage_no INT,invoice_value NUMERIC(20,2) NOT NULL,pph2 NUMERIC(20,2),vendor_account VARCHAR(100),payment_date DATE,notes TEXT,approval_status VARCHAR(30) DEFAULT 'DRAFT',journal_status VARCHAR(30) DEFAULT 'BELUM DIBUAT JURNAL',created_by BIGINT REFERENCES users(id),created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS approvals(id BIGSERIAL PRIMARY KEY,entity_type VARCHAR(40) NOT NULL,entity_id BIGINT NOT NULL,status VARCHAR(30) NOT NULL,submitted_by BIGINT REFERENCES users(id),approved_by BIGINT REFERENCES users(id),return_reason TEXT,submitted_at TIMESTAMPTZ,decided_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS audit_logs(id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id),action VARCHAR(50) NOT NULL,entity_type VARCHAR(50) NOT NULL,entity_id BIGINT,details JSONB,created_at TIMESTAMPTZ DEFAULT NOW());
