require('dotenv').config();
const express=require('express'), cors=require('cors'), jwt=require('jsonwebtoken'), bcrypt=require('bcryptjs');
const {Pool}=require('pg');
const app=express(); const pool=new Pool({connectionString:process.env.DATABASE_URL});
app.use(cors()); app.use(express.json());
app.use(express.static('public'));
const secret=process.env.JWT_SECRET||'change-me';
function auth(req,res,next){const h=req.headers.authorization||'';try{req.user=jwt.verify(h.replace('Bearer ',''),secret);next()}catch(e){res.status(401).json({message:'Sesi tidak valid'})}}
app.get('/api/health',(req,res)=>res.json({ok:true,app:"SOMBERE'",version:'6.2'}));
app.post('/api/login',async(req,res)=>{try{const {username,password}=req.body;const q=await pool.query('select id,username,full_name,role,password_hash,is_active from users where username=$1',[username]);if(!q.rowCount||!q.rows[0].is_active||!await bcrypt.compare(password,q.rows[0].password_hash))return res.status(401).json({message:'Username atau password salah'});const u=q.rows[0];const token=jwt.sign({id:u.id,username:u.username,name:u.full_name,role:u.role},secret,{expiresIn:'8h'});res.json({token,user:{id:u.id,username:u.username,name:u.full_name,role:u.role}})}catch(e){res.status(500).json({message:'Server error'})}});
app.get('/api/dashboard',auth,async(req,res)=>{try{const j=await pool.query("select count(*)::int total, count(*) filter(where status='AKTIF')::int aktif from journal_registers");res.json({journals:j.rows[0],role:req.user.role})}catch(e){res.status(500).json({message:'Server error'})}});
app.get('/api/journals',auth,async(req,res)=>{const q=await pool.query('select * from journal_registers order by id desc limit 500');res.json(q.rows)});
app.post('/api/journals',auth,async(req,res)=>{if(!['Master Administrator','Maker'].includes(req.user.role))return res.status(403).json({message:'Tidak memiliki akses'});const c=await pool.connect();try{await c.query('begin');const d=req.body.journal_date||new Date().toISOString().slice(0,10);const yr=Number(d.slice(0,4)),mo=Number(d.slice(5,7));const s=await c.query("insert into number_sequences(sequence_type,year,last_number) values('JOURNAL',$1,1) on conflict(sequence_type,year) do update set last_number=number_sequences.last_number+1 returning last_number",[yr]);const n=s.rows[0].last_number;const roman=['','I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII'][mo];const no=String(n).padStart(4,'0')+'/KP/'+roman+'/'+yr;const q=await c.query('insert into journal_registers(journal_no,journal_date,cost_name,amount,payee,status,created_by) values($1,$2,$3,$4,$5,\'AKTIF\',$6) returning *',[no,d,req.body.cost_name,req.body.amount,req.body.payee,req.user.id]);await c.query("insert into audit_logs(user_id,action,entity_type,entity_id,details) values($1,'CREATE','JOURNAL',$2,$3)",[req.user.id,q.rows[0].id,JSON.stringify({journal_no:no})]);await c.query('commit');res.status(201).json(q.rows[0])}catch(e){await c.query('rollback');res.status(400).json({message:e.message})}finally{c.release()}});
app.post('/api/journals/:id/cancel',auth,async(req,res)=>{if(!['Master Administrator','Maker'].includes(req.user.role))return res.status(403).json({message:'Tidak memiliki akses'});const q=await pool.query("update journal_registers set status='BATAL',cancel_reason=$1,cancelled_by=$2,cancelled_at=now() where id=$3 and status='AKTIF' returning *",[req.body.reason,req.user.id,req.params.id]);if(!q.rowCount)return res.status(404).json({message:'Register tidak ditemukan/ sudah batal'});await pool.query("insert into audit_logs(user_id,action,entity_type,entity_id,details) values($1,'CANCEL','JOURNAL',$2,$3)",[req.user.id,req.params.id,JSON.stringify({reason:req.body.reason})]);res.json(q.rows[0])});

function allow(roles){return (req,res,next)=>roles.includes(req.user.role)?next():res.status(403).json({message:'Tidak memiliki akses'});}
function roman(m){return ['','I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII'][m]}
app.get('/api/control-cards',auth,async(req,res)=>{const q=await pool.query(`select c.*,u.full_name created_by_name from control_cards c left join users u on u.id=c.created_by order by c.id desc limit 500`);res.json(q.rows)});
app.get('/api/control-cards/:id',auth,async(req,res)=>{const q=await pool.query('select * from control_cards where id=$1',[req.params.id]);if(!q.rowCount)return res.status(404).json({message:'Kartu tidak ditemukan'});const t=await pool.query('select * from control_card_terms where control_card_id=$1 order by term_no',[req.params.id]);res.json({...q.rows[0],terms:t.rows})});
app.post('/api/control-cards',auth,allow(['Master Administrator','Maker']),async(req,res)=>{const b=req.body,c=await pool.connect();try{await c.query('begin');if(!b.job_name||!b.user_name||!b.division_name||!Number(b.procurement_value))throw Error('Data wajib belum lengkap');if(!['TERMIN','MONTHLY'].includes(b.payment_method))throw Error('Metode pembayaran tidak valid');if(b.payment_method==='TERMIN'){const total=(b.terms||[]).reduce((a,x)=>a+Number(x.payment_percentage||0),0);if(Math.abs(total-100)>.001)throw Error('Total persentase termin harus 100%');}const d=b.card_date||new Date().toISOString().slice(0,10),yr=+d.slice(0,4),mo=+d.slice(5,7);const sq=await c.query("insert into number_sequences(sequence_type,year,last_number) values('KK',$1,1) on conflict(sequence_type,year) do update set last_number=number_sequences.last_number+1 returning last_number",[yr]);const no='KK/'+String(sq.rows[0].last_number).padStart(4,'0')+'/DUM/'+roman(mo)+'/'+yr;const q=await c.query(`insert into control_cards(card_no,job_name,contract_no,vendor_name,vendor_pic_name,vendor_pic_phone,user_name,division_name,procurement_value,tax_status,payment_method,duration_type,duration_months,status,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'DRAFT',$14) returning *`,[no,b.job_name,b.contract_no||null,b.vendor_name||null,b.vendor_pic_name||null,b.vendor_pic_phone||null,b.user_name,b.division_name,b.procurement_value,b.tax_status,b.payment_method,b.duration_type||null,b.duration_months||null,req.user.id]);for(const x of (b.terms||[]))await c.query(`insert into control_card_terms(control_card_id,term_no,progress_condition,payment_percentage,term_value,manual_override,override_reason) values($1,$2,$3,$4,$5,$6,$7)`,[q.rows[0].id,x.term_no,x.progress_condition,x.payment_percentage,x.term_value,x.manual_override||false,x.override_reason||null]);await c.query("insert into audit_logs(user_id,action,entity_type,entity_id,details) values($1,'CREATE','CONTROL_CARD',$2,$3)",[req.user.id,q.rows[0].id,JSON.stringify({card_no:no})]);await c.query('commit');res.status(201).json(q.rows[0])}catch(e){await c.query('rollback');res.status(400).json({message:e.message})}finally{c.release()}});
app.post('/api/control-cards/:id/submit',auth,allow(['Master Administrator','Maker']),async(req,res)=>{const c=await pool.connect();try{await c.query('begin');const q=await c.query("update control_cards set status='MENUNGGU APPROVAL',submitted_at=now(),return_reason=null where id=$1 and status in ('DRAFT','DIKEMBALIKAN') returning *",[req.params.id]);if(!q.rowCount)throw Error('Kartu tidak dapat diajukan');await c.query("insert into approvals(entity_type,entity_id,status,submitted_by,submitted_at) values('CONTROL_CARD',$1,'MENUNGGU APPROVAL',$2,now())",[req.params.id,req.user.id]);await c.query("insert into audit_logs(user_id,action,entity_type,entity_id,details) values($1,'SUBMIT','CONTROL_CARD',$2,'{}')",[req.user.id,req.params.id]);await c.query('commit');res.json(q.rows[0])}catch(e){await c.query('rollback');res.status(400).json({message:e.message})}finally{c.release()}});
app.get('/api/approvals/pending',auth,allow(['Master Administrator','Approver']),async(req,res)=>{const q=await pool.query("select * from control_cards where status='MENUNGGU APPROVAL' order by submitted_at");res.json(q.rows)});
app.post('/api/control-cards/:id/decision',auth,allow(['Master Administrator','Approver']),async(req,res)=>{const {decision,reason}=req.body;if(!['APPROVE','RETURN'].includes(decision))return res.status(400).json({message:'Keputusan tidak valid'});if(decision==='RETURN'&&!String(reason||'').trim())return res.status(400).json({message:'Alasan pengembalian wajib diisi'});const c=await pool.connect();try{await c.query('begin');const st=decision==='APPROVE'?'PEMBAYARAN BERJALAN':'DIKEMBALIKAN';const q=await c.query(`update control_cards set status=$1,approved_at=case when $1='PEMBAYARAN BERJALAN' then now() else approved_at end,approved_by=case when $1='PEMBAYARAN BERJALAN' then $2 else approved_by end,return_reason=$3 where id=$4 and status='MENUNGGU APPROVAL' returning *`,[st,req.user.id,reason||null,req.params.id]);if(!q.rowCount)throw Error('Pengajuan tidak ditemukan');await c.query("update approvals set status=$1,approved_by=$2,return_reason=$3,decided_at=now() where entity_type='CONTROL_CARD' and entity_id=$4 and status='MENUNGGU APPROVAL'",[decision==='APPROVE'?'APPROVED':'DIKEMBALIKAN',req.user.id,reason||null,req.params.id]);await c.query("insert into audit_logs(user_id,action,entity_type,entity_id,details) values($1,$2,'CONTROL_CARD',$3,$4)",[req.user.id,decision,req.params.id,JSON.stringify({reason:reason||null})]);await c.query('commit');res.json(q.rows[0])}catch(e){await c.query('rollback');res.status(400).json({message:e.message})}finally{c.release()}});

app.get('*',(req,res)=>{if(!req.path.startsWith('/api/')) res.sendFile(require('path').join(__dirname,'public','index.html'));});
app.listen(process.env.PORT||5050,()=>console.log('SOMBERE Web running on port '+(process.env.PORT||5050)));
